baseURL = 'https://nho1ix.github.io/'
languageCode = 'en-us'
title = 'Random Ideas'
theme = 'lugo'

[params]
  favicon = "/favicon.ico"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
[[module.imports]]
  path = 'github.com/nho1ix/lugo'
